version: '3'
services:
  users-service:
    build: ./Users-Service/
    ports:
      - "4000:4000"
    volumes:
      - ./Users-Service:/app
    environment:
      - PORT=5001
    depends_on:
      - mongodb1
  mongodb1:
    image: mongo


  products-service:
    build: ./Products-service/
    ports:
      - "5000:5000"
    volumes:
      - ./Products-Service:/app
    environment:
      - PORT=5000
    depends_on:
      - mongodb2
  mongodb2:
    image: mongo

  orders-service:
    build: ./Order-service/
    ports:
      - "6000:6000"
    volumes:
      - ./Orders-Service:/app
    environment:
      - PORT=5002
    depends_on:
      - mongodb3
  mongodb3:
     image: mongo

      
  getway-service:
    build: ./gateway/
    ports:
      - "8080:8080"
    volumes:
      - ./Getway-Service:/app
    environment:
      - PORT=5555
    depends_on:
      - users-service
      - products-service
      - orders-service
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq:/var/lib/rabbitmq/

  frontend:
    build: ./Front-end-e-co/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - PORT=3000
    depends_on:
      - getway-service