version: '3'
services:
  users-service:
    build: ./Users-Service/
    container_name: 'users-service'
    ports:
      - "4000:4000"
    volumes:
      - ./Users-Service:/app
    environment:
      - PORT=5001
      - MONGODB_URI=${USER_MONGODB_URI}
    depends_on:
      - rabbitmq


  products-service:
    build: ./Products-service/
    container_name: 'products-service'
    ports:
      - "5000:5000"
    volumes:
      - ./Products-Service:/app
    environment:
      - PORT=5000
      - MONGODB_URI=${PRODUCT_MONGODB_URI}
    depends_on:
      - rabbitmq

  orders-service:
    build: ./Order-service/
    container_name: 'orders-service'
    ports:
      - "6000:6000"
    volumes:
      - ./Order-service:/app
    environment:
      - PORT=5002
      - MONGODB_URI=${ORDER_MONGODB_URI}
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq:/var/lib/rabbitmq/

  frontend:
    build: ./Front-end-e-co/
    ports:
      - "3000:3000"
    volumes:
      - ./Front-end-e-co/:/app
    environment:
      - PORT=3000
    depends_on:
      - nginx-proxy

  nginx-proxy:
    build: ./proxy/
    depends_on:
      - products-service
      - users-service
      - orders-service
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80