version: '3.8'

services:
  order-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "${PORT}:${PORT}"
    env_file: 
      - ./.env