apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: ecommerce.chily.io.vn #  Thay bằng tên miền sử dụng Cloudflare Tunnel
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: users-service
            port:
              number: 5001
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: orders-service
            port:
              number: 5002
      - path: /product
        pathType: Prefix
        backend:
          service:
            name: products-service
            port:
              number: 5000
