apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: eco-web-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: lykieuchi/ecommerce-web-user-service:3.0
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri-secret
              key: USER_MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: eco-web-microservices
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001