apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.users.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.users.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.users.port }}
      targetPort: {{ .Values.users.port }}
      