namespace: eco-web-microservices

ingress:
  name: ecommerce-ingress
  className: nginx
  annotations:
    rewriteTarget: /$2
    useRegex: "true"
  frontendPath: /()(.*)
  pathType: ImplementationSpecific

configMap:
  searchServiceUrl: "http://search-service:1234"
  rsServiceUrl: "http://rs-service:1357"
  productServiceUrl: "http://products-service:5000"
  userServiceUrl: "http://users-service:5001"
  orderServiceUrl: "http://orders-service:5002"
  gatewayServiceUrl: "http://gateway-service:5555"
  chatServiceUrl: "http://chat-service:5008"
  payServiceUrl: "http://pay-service:5009"
  frontendServiceUrl: "http://frontend:3000"
  wsServiceUrl: "http://chat-service:5008"
  

mongodb:
  secrets:
    userUri: "bW9uZ29kYitzcnY6Ly8yMDUyMTEzMTpoYXpha2FjaGk2OUBjbHVzdGVyMC5uY2JhbGl5Lm1vbmdvZGIubmV0L1VzZXItV2F0Y2hfc2hvcD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA=="
    productUri: "bW9uZ29kYitzcnY6Ly8yMDUyMTEzMTpoYXpha2FjaGk2OUBjbHVzdGVyMC5uY2JhbGl5Lm1vbmdvZGIubmV0L1dhdGNoX3Nob3A/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA="
    orderUri: "bW9uZ29kYitzcnY6Ly8yMDUyMTEzMTpoYXpha2FjaGk2OUBjbHVzdGVyMC5uY2JhbGl5Lm1vbmdvZGIubmV0L09yZGVyLVdhdGNoX3Nob3A/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA="
    chatUri: "bW9uZ29kYitzcnY6Ly8yMDUyMTEzMTpoYXpha2FjaGk2OUBjbHVzdGVyMC5uY2JhbGl5Lm1vbmdvZGIubmV0L1dhdGNoc2hvcF9DaGF0P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw"

paypal:
  PAYPAL_CLIENT_ID: "AYQ_XBnAGfXPBw43yGEDl_XJJqENJXsKPcSbM6lyVqowKMLlhQFei5XP1zUdnug5YwXxA-NZ9lvzZT42"
  PAYPAL_CLIENT_SECRET: "EAYgWg1rfE6CZMfXS5oQRy-y8cfKgaKhXHhcKTwtFJ58QLhhrdkIVrjWg6OzvgvwHrO1S6DnidHEh-m5"
  PAYPAL_API: "https://api-m.sandbox.paypal.com"

stripe:
  STRIPE_SECRET_KEY: "sk_test_51QFV1OJu8ujkgWdNlz3WkbsYRiyllmKEWFxb1XnSvq3CHLl64w47Vf5vPb3ZCmDln5ALACBJv7KkrBAzrR14ynNE00OTop66zk"

tag: 4e11591611a6a6a9666295a59f3725ed47f957b9

frontend:
  name: frontend
  replicas: 4
  image:
    repository: lykieuchi/frontend
  port: 3000

orders:
  name: orders-service
  replicas: 1
  image:
    repository: lykieuchi/order-service
  port: 5002

products:
  name: products-service
  replicas: 1
  image:
    repository: lykieuchi/product-service
  port: 5000

users:
  name: users-service
  replicas: 1
  image:
    repository: lykieuchi/users-service
  port: 5001

gateway:
  name: gateway-service
  replicas: 1
  image:
    repository: lykieuchi/gateway-service
  port: 5555

payment:
  name: pay-service
  replicas: 1
  image:
    repository: lykieuchi/pay-service
  port: 5009

chat:
  name: chat-service
  replicas: 1
  image:
    repository: lykieuchi/chat-service
  port: 5008