apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  SEARCH_SERVICE_URL: {{ .Values.configMap.searchServiceUrl }}
  RS_SERVICE_URL: {{ .Values.configMap.rsServiceUrl }}
  PRODUCT_SERVICE_URL: {{ .Values.configMap.productServiceUrl }}
  USER_SERVICE_URL: {{ .Values.configMap.userServiceUrl }}
  ORDER_SERVICE_URL: {{ .Values.configMap.orderServiceUrl }}