apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  USER_MONGODB_URI: {{ .Values.mongodb.secrets.userUri }}
  PRODUCT_MONGODB_URI: {{ .Values.mongodb.secrets.productUri }}
  ORDER_MONGODB_URI: {{ .Values.mongodb.secrets.orderUri }}