name: Deploy to Kubernetes

on:
  push:
    branches:
      - Add-chat-service 

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/nginx-configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/users-deployment.yaml
          kubectl apply -f k8s/products-deployment.yaml
          kubectl apply -f k8s/
  check:
    needs: deploy
    strategy:
      matrix:
        service: ['users', 'products']
    runs-on: self-hosted
    steps:
      - name: Check ${{ matrix.service }} deployment
        run: kubectl rollout status deployment/${{ matrix.service }}-service -n eco-web-microservices


