name: Deploy to Kubernetes

on:
  push:
    branches:
      - Add-chat-service 

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: [self-hosted, kubernetes]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f k8s/nginx-configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/users-deployment.yaml
          kubectl apply -f k8s/products-deployment.yaml
          kubectl apply -f k8s/
      - name: Check deployment status
        run: |
          kubectl rollout status deployment/users-service
